// Datos simulados (mock) para la plataforma Unveil UGC
// Este archivo contiene datos de ejemplo para pruebas locales
import { Offer, Incentive, Campaign } from '../models/Offer';
import { User } from '../models/User';

// Lista de categorías/sectores disponibles para seleccionar intereses
export const UGC_CATEGORIES = [
  'Gastronomía',
  'Moda',
  'Viajes',
  'Belleza',
  'Tecnología',
  'Fitness',
  'Decoración',
  'Eventos Locales',
  'Lifestyle',
  'Gaming',
  'Educación',
  'Mascotas',
  'Arte',
  'Cine',
  'Deportes',
  'Música',
  'Cultura'
];

// Países disponibles para el registro de usuario
export const COUNTRIES = [
  'Argentina',
  'Chile',
  'Colombia',
  'México',
  'Perú',
  'Uruguay',
  'España',
  'Francia',
  'Italia',
  'Alemania',
  'Portugal',
  'Reino Unido',
  'Países Bajos',
  'Bélgica',
  'Suiza',
  'Austria'
];

// Ciudades/provincias por país para el registro
export const CITIES_BY_COUNTRY: { [key: string]: string[] } = {
  'Argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata'],
  'Chile': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta'],
  'Colombia': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'],
  'México': ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana'],
  'Perú': ['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Piura'],
  'Uruguay': ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras', 'Rivera'],
  'España': [
    'A Coruña',
    'Álava',
    'Albacete',
    'Alicante',
    'Almería',
    'Asturias',
    'Ávila',
    'Badajoz',
    'Barcelona',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Cantabria',
    'Castellón',
    'Ciudad Real',
    'Córdoba',
    'Cuenca',
    'Girona',
    'Granada',
    'Guadalajara',
    'Guipúzcoa',
    'Huelva',
    'Huesca',
    'Islas Baleares',
    'Jaén',
    'La Rioja',
    'Las Palmas',
    'León',
    'Lleida',
    'Lugo',
    'Madrid',
    'Málaga',
    'Murcia',
    'Navarra',
    'Ourense',
    'Palencia',
    'Pontevedra',
    'Salamanca',
    'Santa Cruz de Tenerife',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Vizcaya',
    'Zamora',
    'Zaragoza'
  ],
  'Francia': [
    'Île-de-France',
    'Auvergne-Rhône-Alpes',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Hauts-de-France',
    'Grand Est',
    'Provence-Alpes-Côte d\'Azur',
    'Pays de la Loire',
    'Normandie',
    'Bretagne',
    'Bourgogne-Franche-Comté',
    'Centre-Val de Loire',
    'Corse'
  ],
  'Italia': [
    'Lombardía',
    'Lacio',
    'Campania',
    'Sicilia',
    'Véneto',
    'Emilia-Romaña',
    'Piamonte',
    'Apulia',
    'Toscana',
    'Calabria',
    'Sardegna',
    'Liguria',
    'Marcas',
    'Abruzo',
    'Friuli-Venecia Julia',
    'Trentino-Alto Adigio',
    'Umbría',
    'Basilicata',
    'Molise',
    'Valle de Aosta'
  ],
  'Alemania': [
    'Baviera',
    'Renania del Norte-Westfalia',
    'Baden-Württemberg',
    'Baja Sajonia',
    'Hesse',
    'Sajonia',
    'Renania-Palatinado',
    'Berlín',
    'Schleswig-Holstein',
    'Brandeburgo',
    'Sajonia-Anhalt',
    'Turingia',
    'Hamburgo',
    'Mecklemburgo-Pomerania Occidental',
    'Sarre',
    'Bremen'
  ],
  'Portugal': [
    'Lisboa',
    'Oporto',
    'Braga',
    'Setúbal',
    'Aveiro',
    'Leiria',
    'Faro',
    'Coímbra',
    'Madeira',
    'Azores',
    'Viseu',
    'Viana do Castelo',
    'Vila Real',
    'Braganza',
    'Guarda',
    'Castelo Branco',
    'Évora',
    'Beja',
    'Portalegre'
  ],
  'Reino Unido': [
    'Inglaterra',
    'Escocia',
    'Gales',
    'Irlanda del Norte',
    'Gran Londres',
    'Manchester',
    'Birmingham',
    'Leeds',
    'Glasgow',
    'Liverpool',
    'Newcastle',
    'Sheffield',
    'Bristol',
    'Edimburgo',
    'Cardiff'
  ],
  'Países Bajos': [
    'Holanda Septentrional',
    'Holanda Meridional',
    'Brabante Septentrional',
    'Gelderland',
    'Utrecht',
    'Limburg',
    'Overijssel',
    'Frisia',
    'Groningen',
    'Drenthe',
    'Zelanda',
    'Flevoland'
  ],
  'Bélgica': [
    'Bruselas',
    'Amberes',
    'Gante',
    'Charleroi',
    'Lieja',
    'Brujas',
    'Namur',
    'Lovaina',
    'Mons',
    'Aalst'
  ],
  'Suiza': [
    'Zúrich',
    'Ginebra',
    'Basilea',
    'Berna',
    'Lausana',
    'Lucerna',
    'San Galo',
    'Lugano',
    'Winterthur',
    'Friburgo'
  ],
  'Austria': [
    'Viena',
    'Baja Austria',
    'Alta Austria',
    'Estiria',
    'Tirol',
    'Carintia',
    'Salzburgo',
    'Vorarlberg',
    'Burgenland'
  ]
};

// Mock incentives for offers
const incentives: Incentive[] = [
  {
    type: 'Cena',
    description: 'Cena gratuita para 2 personas',
    value: 50,
  },
  {
    type: 'Hospedaje',
    description: 'Noche de hotel valorada en 100€',
    value: 100,
  },
  {
    type: 'Descuento',
    description: 'Vale de descuento del 50%',
    value: 25,
  },
  {
    type: 'Producto',
    description: 'Producto completo de nuestra colección',
    value: 75,
  },
  {
    type: 'Experiencia',
    description: 'Experiencia completa para 2 personas',
    value: 120,
  },
];

// Mock users data
export const MOCK_USERS: User[] = [
  {
    id: '1',
    fullName: 'Ana Martínez',
    email: 'ana.martinez@email.com',
    password: 'A1@12345',
    role: 'creator',
    country: 'Argentina',
    city: 'Buenos Aires',
    socialMedia: [
      { platform: 'instagram', username: 'ana.ugc' },
      { platform: 'tiktok', username: 'ana.tiktok' }
    ],
    stats: {
      campaigns: 5,
      reviews: [
        { textReview: 'Excelente colaboración y comunicación.', businessId: '4', stars: 5 },
        { textReview: 'Muy profesional', businessId: '4', stars: 4 }
      ],
      level: 'Intermedio'
    },
    interests: ['Gastronomía', 'Moda']
  },
  {
    id: '2',
    fullName: 'Carlos López',
    email: 'carlos.lopez@email.com',
    password: 'C1@12345',
    role: 'creator',
    country: 'México',
    city: 'Guadalajara',
    socialMedia: [
      { platform: 'youtube', username: 'carlos.travel' }
    ],
    stats: {
      campaigns: 10,
      reviews: [
        { textReview: 'Gran experiencia, muy recomendable.', businessId: '5', stars: 5 },
        { textReview: 'Contenido creativo', businessId: '6', stars: 4 }
      ],
      level: 'Avanzado'
    },
    interests: ['Viajes', 'Tecnología']
  },
  {
    id: '3',
    fullName: 'María García',
    email: 'maria.garcia@email.com',
    password: 'M1@12345',
    role: 'creator',
    country: 'España',
    city: 'Barcelona',
    socialMedia: [
      { platform: 'instagram', username: 'maria.beauty' }
    ],
    stats: {
      campaigns: 3,
      reviews: [
        { textReview: 'Contenido profesional', businessId: '4', stars: 5 }
      ],
      level: 'Principiante'
    },
    interests: ['Belleza', 'Moda']
  },
  {
    id: '4',
    fullName: 'Restaurante La Madrileña',
    email: 'info@lamadrilena.com',
    password: 'R1@12345',
    role: 'business',
    country: 'España',
    city: 'Madrid',
    socialMedia: [],
    stats: {
      campaigns: 0,
      reviews: [],
      level: 'N/A'
    },
    interests: ['Gastronomía']
  },
  {
    id: '5',
    fullName: 'Hotel Costa del Sol',
    email: 'info@hotelcostadelsol.com',
    password: 'H1@12345',
    role: 'business',
    country: 'España',
    city: 'Málaga',
    socialMedia: [],
    stats: {
      campaigns: 0,
      reviews: [],
      level: 'N/A'
    },
    interests: ['Viajes', 'Turismo']
  },
  {
    id: '6',
    fullName: 'Festival de Verano',
    email: 'info@festivalverano.com',
    password: 'F1@12345',
    role: 'business',
    country: 'España',
    city: 'Madrid',
    socialMedia: [],
    stats: {
      campaigns: 0,
      reviews: [],
      level: 'N/A'
    },
    interests: ['Eventos', 'Música']
  }
];

// Mockup de Negocios (para hacer match con ofertas)
export const MOCK_BUSINESSES = [
  {
    id_usuario: '4',
    nombreEmpresa: 'Restaurante La Madrileña',
    cantidadEmpleados: 20,
    ubicacion: { pais: 'España', ciudad: 'Madrid' },
    tipoNegocio: 'Restaurante',
    categoria: 'Gastronomía',
    categorias: ['Gastronomía', 'Eventos Locales', 'Cultura'],
  },
  {
    id_usuario: '5',
    nombreEmpresa: 'Hotel Vista Mar',
    cantidadEmpleados: 50,
    ubicacion: { pais: 'España', ciudad: 'Barcelona' },
    tipoNegocio: 'Hotel',
    categoria: 'Viajes',
    categorias: ['Viajes', 'Turismo', 'Lifestyle'],
  },
  {
    id_usuario: '6',
    nombreEmpresa: 'TechStore',
    cantidadEmpleados: 15,
    ubicacion: { pais: 'España', ciudad: 'Madrid' },
    tipoNegocio: 'Tienda',
    categoria: 'Tecnología',
    categorias: ['Tecnología', 'Gaming', 'Educación'],
  },
];

// Ofertas simuladas de negocios locales
export const MOCK_OFFERS: Offer[] = [
  {
    id: '1',
    businessId: '4',
    businessName: 'Restaurante La Madrileña',
    title: 'Promociona nuestro nuevo menú',
    description: 'Crear 3 stories sobre nuestra nueva carta de temporada destacando los platos estrella.',
    category: 'Gastronomía',
    requiredLevel: 'Principiante',
    incentive: incentives[0],
    status: 'active',
    createdAt: new Date('2025-04-01'),
    expiresAt: new Date('2025-05-01'),
    country: 'España',
    city: 'Madrid',
    isRemote: false,
    platformsRequired: ['Instagram'],
    contentType: ['story'],
    deadline: new Date('2025-04-25'),
    mustAttendEvent: true,
    exclusive: false,
    customTags: ['cena', 'temporada', 'gastronomía'],
  },
  {
    id: '2',
    businessId: '5',
    businessName: 'Boutique Eleganza',
    title: 'Muestra nuestra nueva colección',
    description: 'Crear contenido con 2 prendas de nuestra nueva colección de primavera.',
    category: 'Moda',
    requiredLevel: 'Principiante',
    incentive: incentives[3],
    status: 'active',
    createdAt: new Date('2025-04-05'),
    expiresAt: new Date('2025-05-05'),
    country: 'España',
    city: 'Barcelona',
    isRemote: true,
    platformsRequired: ['Instagram', 'TikTok'],
    genderRequired: 'female',
    contentType: ['post', 'story'],
    deadline: new Date('2025-04-20'),
    mustAttendEvent: false,
    exclusive: true,
    customTags: ['moda', 'colección', 'primavera'],
  },
  {
    id: '3',
    businessId: '6',
    businessName: 'Hotel Vista Mar',
    title: 'Promociona nuestra suite premium',
    description: 'Crear un reel mostrando las instalaciones de nuestra suite con vistas al mar.',
    category: 'Viajes',
    requiredLevel: 'Principiante',
    incentive: incentives[1],
    status: 'active',
    createdAt: new Date('2025-04-08'),
    expiresAt: new Date('2025-05-08'),
    country: 'España',
    city: 'Valencia',
    isRemote: false,
    platformsRequired: ['Instagram', 'YouTube'],
    languagesRequired: ['es', 'en'],
    contentType: ['reel', 'story'],
    deadline: new Date('2025-04-30'),
    mustAttendEvent: true,
    exclusive: true,
    customTags: ['viajes', 'suite', 'premium'],
  },
  {
    id: '4',
    businessId: '6',
    businessName: 'Spa Natural Beauty',
    title: 'Muestra nuestros tratamientos faciales',
    description: 'Crear contenido sobre la experiencia de nuestro tratamiento facial estrella.',
    category: 'Belleza',
    requiredLevel: 'Intermedio',
    incentive: incentives[4],
    status: 'active',
    createdAt: new Date('2025-04-10'),
    expiresAt: new Date('2025-05-10'),
    country: 'España',
    city: 'Madrid',
    isRemote: false,
    platformsRequired: ['Instagram'],
    contentType: ['post', 'story'],
    deadline: new Date('2025-04-25'),
    mustAttendEvent: true,
    exclusive: false,
    customTags: ['belleza', 'spa', 'tratamiento'],
  },
  {
    id: '5',
    businessId: '5',
    businessName: 'TechStore',
    title: 'Review de nuestro nuevo gadget',
    description: 'Crear un video review de nuestro último lanzamiento tecnológico.',
    category: 'Tecnología',
    requiredLevel: 'Principiante',
    incentive: incentives[3],
    status: 'active',
    createdAt: new Date('2025-04-12'),
    expiresAt: new Date('2025-05-12'),
    country: 'España',
    city: 'Madrid',
    isRemote: true,
    platformsRequired: ['YouTube', 'TikTok'],
    contentType: ['video'],
    deadline: new Date('2025-05-01'),
    mustAttendEvent: false,
    exclusive: true,
    customTags: ['tecnología', 'gadget', 'review'],
  },
  {
    id: '6',
    businessId: '4',
    businessName: 'GymFit Center',
    title: 'Muestra nuestra rutina de entrenamiento',
    description: 'Crear contenido realizando nuestra rutina de entrenamiento exclusiva.',
    category: 'Fitness',
    requiredLevel: 'Principiante',
    incentive: incentives[2],
    status: 'active',
    createdAt: new Date('2025-04-15'),
    expiresAt: new Date('2025-05-15'),
    country: 'España',
    city: 'Barcelona',
    isRemote: false,
    platformsRequired: ['Instagram', 'TikTok'],
    contentType: ['reel', 'video'],
    deadline: new Date('2025-05-10'),
    mustAttendEvent: true,
    exclusive: false,
    customTags: ['fitness', 'entrenamiento', 'rutina'],
  },
  {
    id: '7',
    businessId: '5',
    businessName: 'Home & Deco',
    title: 'Muestra nuestros productos en tu hogar',
    description: 'Crear contenido integrando algunos de nuestros productos de decoración en tu espacio.',
    category: 'Decoración',
    requiredLevel: 'Principiante',
    incentive: incentives[3],
    status: 'active',
    createdAt: new Date('2025-04-18'),
    expiresAt: new Date('2025-05-18'),
    country: 'España',
    city: 'Valencia',
    isRemote: true,
    platformsRequired: ['Instagram'],
    contentType: ['post', 'story'],
    deadline: new Date('2025-05-15'),
    mustAttendEvent: false,
    exclusive: false,
    customTags: ['decoración', 'hogar', 'lifestyle'],
  },
  {
    id: '8',
    businessId: '6',
    businessName: 'Festival de Verano',
    title: 'Promociona nuestro evento',
    description: 'Crear contenido promocionando nuestro festival de música y gastronomía local.',
    category: 'Eventos Locales',
    requiredLevel: 'Principiante',
    incentive: incentives[4],
    status: 'active',
    createdAt: new Date('2025-04-20'),
    expiresAt: new Date('2025-05-20'),
    country: 'España',
    city: 'Madrid',
    isRemote: false,
    platformsRequired: ['Instagram', 'TikTok', 'YouTube'],
    contentType: ['post', 'story', 'video'],
    deadline: new Date('2025-05-15'),
    mustAttendEvent: true,
    exclusive: true,
    customTags: ['festival', 'música', 'gastronomía', 'evento'],
  },
];

// Estados posibles de las campañas
export const MOCK_CAMPAIGNS_STATUS = [
  'active',
  'completed',
  'pending',
  'rejected',
  'canceled',
];

// Nota: Las campañas ahora se manejan a través de userProposals en matchingService.ts
